version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.1.0
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: 'anchore/anchore-engine:latest'
      - anchore/image_scan:
          image_name: 'btodhunter/circleci-demo:latest'
          private_registry: True
          timeout: '500'
